[package]
name = "neoenv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
inquire = "0.7.5"
skim = "0.10.4"
xdg = "2.5.2"
