name: "Format"

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: setup rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: format
        run: |
          $HOME/.cargo/bin/cargo fmt


      - name: Create PR
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "[Automated] cargo fmt"
          gh pr create --title "cargo fmt"
